CC = arm-linux-gnueabihf-gcc
CXX = arm-linux-gnueabihf-g++

CPPFLAGS = -I .
CFLAGS =-g -std=gnu99 -O1 -Wall
CXXFLAGS = -g -std=gnu++11 -O1 -Wall
LDFLAGS = -lrt -lpthread

SOURCES = main.c mzapo/mzapo_phys.c mzapo/mzapo_parlcd.c
SOURCES += fonts/font_prop14x16.c fonts/font_rom8x16.c
SOURCES += utils/lcd.c utils/led.c utils/servo.c
SOURCES += gui/fbuffer.c gui/menu.c
TARGET_EXE = ap8

ifeq ($(TARGET_IP)$(filter run,$(MAKECMDGOALS)),run)
$(warning The target IP address is not set)
$(warning Run as "TARGET_IP=192.168.202.xxx make run" or modify Makefile)
TARGET_IP ?= 192.168.202.xxx
endif

TARGET_DIR ?= /tmp/$(shell whoami)
TARGET_USER ?= root
SSH_OPTIONS=-i /opt/zynq/ssh-connect/mzapo-root-key

OBJECTS += $(filter %.o,$(SOURCES:%.c=%.o))

#$(warning OBJECTS=$(OBJECTS))

LINKER = $(CXX)
LDFLAGS += $(CXXFLAGS) $(CPPFLAGS)

%.o:%.c
	$(CC) $(CFLAGS) -c $<

all: $(TARGET_EXE)

$(TARGET_EXE): $(OBJECTS)
	$(LINKER) $(LDFLAGS) -L. $(notdir $^) -o $@

.PHONY : dep all run copy-executable debug

dep: depend

depend: $(SOURCES) *.h
	echo '# autogenerated dependencies' > depend
ifneq ($(filter %.c,$(SOURCES)),)
	$(CC) $(CFLAGS) $(CPPFLAGS) -w -E -M $(filter %.c,$(SOURCES)) \
	  >> depend
endif

clean:
	rm -f *.o *.a $(OBJECTS) $(TARGET_EXE) connect.gdb depend

copy-executable: $(TARGET_EXE)
	ssh $(SSH_OPTIONS) -t $(TARGET_USER)@$(TARGET_IP) killall gdbserver 1>/dev/null 2>/dev/null || true
	ssh $(SSH_OPTIONS) $(TARGET_USER)@$(TARGET_IP) mkdir -p $(TARGET_DIR)
	scp $(SSH_OPTIONS) $(TARGET_EXE) $(TARGET_USER)@$(TARGET_IP):$(TARGET_DIR)/$(TARGET_EXE)

run: copy-executable $(TARGET_EXE)
	ssh $(SSH_OPTIONS) -t $(TARGET_USER)@$(TARGET_IP) $(TARGET_DIR)/$(TARGET_EXE)

debug: copy-executable $(TARGET_EXE)
	xterm -e ssh $(SSH_OPTIONS) -t $(TARGET_USER)@$(TARGET_IP) gdbserver :12345 $(TARGET_DIR)/$(TARGET_EXE) &
	sleep 2
	echo >connect.gdb "target extended-remote $(TARGET_IP):12345"
	echo >>connect.gdb "b main"
	echo >>connect.gdb "c"
	ddd --debugger gdb-multiarch -x connect.gdb $(TARGET_EXE)

-include depend
